version: '3.9'

services:
  
  # --- ¡IMPORTANTE! SERVICIO DEL BUS ESB ---
  # He añadido este servicio como placeholder para el bus de tu profesor.
  # DEBES ajustar el 'build' para que apunte a la carpeta donde
  # está el Dockerfile del código de tu profesor.
  esb_bus:
    build: ./esb_bus  # <-- ⚠️ ¡AJUSTA ESTA RUTA!
    container_name: esb_bus
    ports:
      - "8000:8000"  # <-- ⚠️ Ajusta este puerto al que usa el ESB (usé 8000 como ejemplo)
    networks:
      - soa-net
  # ----------------------------------------

  servicio_usuarios:
    build: ./servicio_usuarios
    container_name: servicio_usuarios
    # ports: - "5100:5100"  <-- Ya no es necesario
    environment:
      # Variables de la BD
      - DB_HOST=postgres
      - DB_NAME=gestor_correos
      - DB_USER=gestor_user
      - DB_PASS=1234
      # Nuevas variables del ESB
      - ESB_HOST=esb_bus      # <-- Conecta con el nombre del servicio del bus
      - ESB_PORT=8000         # <-- Debe coincidir con el puerto del bus
      - SERVICE_NAME=usuarios # <-- Nombre para registrarse en el bus
    depends_on:
      - postgres
      - esb_bus               # <-- Nueva dependencia
    networks:
      - soa-net

  servicio_correos:
    build: ./servicio_correos
    container_name: servicio_correos
    # ports: - "5200:5200"  <-- Ya no es necesario
    environment:
      # Variable de Elasticsearch
      - ES_HOST=http://elasticsearch:9200
      # Nuevas variables del ESB
      - ESB_HOST=esb_bus
      - ESB_PORT=8000
      - SERVICE_NAME=correos
    depends_on:
      - elasticsearch
      - esb_bus               # <-- Nueva dependencia
    networks:
      - soa-net

  servicio_logs:
    build: ./servicio_logs
    container_name: servicio_logs
    # ports: - "5400:5400"  <-- Ya no es necesario
    environment:
      # Variables de la BD
      - DB_HOST=postgres
      - DB_NAME=gestor_correos
      - DB_USER=gestor_user
      - DB_PASS=1234
      # Nuevas variables del ESB
      - ESB_HOST=esb_bus
      - ESB_PORT=8000
      - SERVICE_NAME=logs
    depends_on:
      - postgres
      - esb_bus               # <-- Nueva dependencia
    networks:
      - soa-net

  servicio_pst:
    build: ./servicio_pst
    container_name: servicio_pst
    # ports: - "5300:5300"  <-- Ya no es necesario
    environment:
      # Variables de la BD
      - DB_HOST=postgres
      - DB_NAME=gestor_correos
      - DB_USER=gestor_user
      - DB_PASS=1234
      # Nuevas variables del ESB
      - ESB_HOST=esb_bus
      - ESB_PORT=8000
      - SERVICE_NAME=pst
    volumes:
      - ./data/pst_files:/app/pst_files
    depends_on:
      - postgres
      - esb_bus               # <-- Nueva dependencia
    networks:
      - soa-net

  # --- SERVICIOS BASE (Sin cambios) ---

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=gestor_correos
      - POSTGRES_USER=gestor_user
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - soa-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - soa-net

networks:
  soa-net:
    driver: bridge

volumes:
  pg_data:
  es_data: